/*
	File: fn_itemWeight.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Gets the items weight and returns it.
*/
private["_item"];
_item = [_this,0,"",[""]] call BIS_fnc_param;
if(_item == "") exitWith {};

switch (_item) do
{
	case "oilu": {6};
	case "oilp": {3};
	case "heroinu": {6};
	case "heroinp": {4};
	case "cannabis": {4};
	case "marijuana": {3};
	case "apple": {1};
	case "water": {1};
	case "rabbit": {1};
	case "salema": {2};
	case "ornate": {2};
	case "mackerel": {4};
	case "tuna": {6};
	case "mullet": {4};
	case "catshark": {6};
	case "turtle": {6};
	case "fishing": {2};
	case "turtlesoup": {2};
	case "donuts": {1};
	case "coffee": {1};
	case "fuelE": {1};
	case "fuelF": {4};
	case "money": {0};
	case "pickaxe": {2};
	case "copperore": {4};
	case "ironore": {5};
	case "copper_r": {3};
	case "iron_r": {3};
	case "sand": {3};
	case "salt": {3};
	case "salt_r": {1};
	case "glass": {1};
	case "diamond": {4};
	case "diamondc": {2};
	case "cocaine": {6};
	case "cocainep": {4};
	case "spikeStrip": {10};
	case "rock": {6};
	case "cement": {5};
	case "goldbar": {12};
	case "blastingcharge": {15};
	case "boltcutter": {5};
	case "defusekit": {2};
	case "storagesmall": {5};
	case "storagebig": {10};
	case "puranium": {2};
    case "ipuranium": {2};
    case "uranium1": {4};
    case "uranium2": {3};
    case "uranium3": {3};
    case "uranium4": {3};
    case "uranium": {3};
	case "iuranium4": {3};
	case "iuranium": {3};
	case "gpstracker": {2};
	case "zipties": {2};
	case "ana": {1};
	case "bw": {3};
	case "methu": {6};
    case "methp": {4};
	case "lsdu": {5};
	case "lsdp": {4};
	case "mull": {2};
	case "uwsl": {5};
	case "gl": {12};
	case "rabbitf": {2};
	case "henraw": {1};
	case "roosterraw": {1};
	case "goatraw": {2};
	case "goatrawf": {3};
	case "sheepraw": {2};
	case "sheeprawf": {3};
	case "doen": {1};
	case "rabbitfp": {1};
	case "goatrawfp": {2};
	case "jame": {2};
	case "mauer": {10};
	case "kegel": {8};
	case "gsg": {16};
	case "gsn": {4};
	case "ggn": {6};
	case "gsm": {8};
	case "sfb": {2};
	case "gab": {1};
	case "ghy": {1};
	case "di": {2};
	case "ben": {1};
	case "sig": {3};
	case "tet": {2};
	case "guh": {1};
	case "prl": {2};
	case "rio": {5};
	case "rig": {2};
	case "rip": {4};
	case "rib": {4};
	case "stt": {9};
	case "a1": {5};
	case "a2": {1};
	case "a3": {2};
	case "a4": {1};
	case "a5": {5};
	case "a6": {3};
	case "a7": {1};
	case "a8": {2};
	case "a9": {2};
	case "a0": {4};
	case "a10": {1};
	case "a11": {1};
	case "a12": {3};
	case "14": {4};
	case "15": {42};
	case "16": {38};
	case "17": {14};
	case "18": {3};
	case "20": {5};
	case "21": {2};
	
	default {1};
};
